apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service
  labels:
    app: books-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
      - name: books-service
        image: moamrn:books-service 
        ports:
        - containerPort: 50051
        env:
        - name: MONGO_URI
          value: "mongodb://library-mongodb:27017/library" 
